sets up destroy inputs for common actions

diff --git a/.github/actions/s3-static-site/action.yml b/.github/actions/s3-static-site/action.yml
--- a/.github/actions/s3-static-site/action.yml
+++ b/.github/actions/s3-static-site/action.yml
@@ -24,10 +24,14 @@ inputs:
     description: AWS Region where the S3 bucket is to be created
     required: false
     default: ap-southeast-2
+  destroy:
+    description: Whether to destroy the infrastructure. Values are 'true', 'soft' or 'false'
+    required: false
+    default: "false"
   soft_destroy:
     description: Whether to destroy the bucket and CloudFront distribution
     required: false
-    default: false
+    default: "false"
 outputs:
   bucket-name:
     description: The name of the S3 bucket created
@@ -44,6 +48,12 @@ runs:
         action_start_ts=$(date +%s)
         echo "ts=$action_start_ts" >> $GITHUB_OUTPUT
         echo "ACTION_PATH=$(realpath ${{ github.action_path }})" >> $GITHUB_ENV
+        valid_values=("true" "soft" "false")
+        if [[ ! " ${valid_values[@]} " =~ " ${{ inputs.destroy }} " ]]; then
+          echo "Invalid value for 'destroy' input: ${{ inputs.destroy }}. Allowed values are 'true', 'soft', or 'false'."
+          exit 1
+        fi
+        echo "Running in destroy mode: ${{ inputs.destroy }}"
 
     - name: Assemble Website Domain
       id: domain
@@ -69,7 +79,7 @@ runs:
         echo "name=$domain_name" >> $GITHUB_OUTPUT
 
     - name: Bootstrap S3 Static Site Bucket for ${{ inputs.module }} ${{ inputs.environment }}
-      if: ${{ !inputs.soft_destroy }}
+      if: ${{ inputs.destroy == 'false' }}
       uses: Imagimaps/common-actions/.github/actions/deploy-tf@main
       with:
         environment: ${{ inputs.environment }}
@@ -83,6 +93,7 @@ runs:
         aws_region: ${{ inputs.aws_region }}
 
     - name: Request Cert for ${{ inputs.module }} ${{ inputs.environment }}
+      if: ${{ inputs.destroy == 'false' }}
       uses: Imagimaps/common-actions/.github/actions/deploy-tf@main
       with:
         environment: ${{ inputs.environment }}
@@ -97,7 +108,7 @@ runs:
         aws_region: ${{ inputs.aws_region }}
 
     - name: Setup CDN for ${{ inputs.module }} ${{ inputs.environment }}
-      if: ${{ !inputs.soft_destroy }}
+      if: ${{ inputs.destroy == 'false' }}
       uses: Imagimaps/common-actions/.github/actions/deploy-tf@main
       with:
         environment: ${{ inputs.environment }}
@@ -112,7 +123,7 @@ runs:
         aws_region: ${{ inputs.aws_region }}
 
     - name: Destroy CDN for ${{ inputs.module }} ${{ inputs.environment }}
-      if: ${{ inputs.soft_destroy }}
+      if: ${{ inputs.destroy != 'false' }}
       uses: Imagimaps/common-actions/.github/actions/deploy-tf@main
       with:
         environment: ${{ inputs.environment }}
@@ -125,10 +136,10 @@ runs:
         aws_role_arn: ${{ inputs.aws_role_arn }}
         aws_account_id: ${{ inputs.aws_account_id }}
         aws_region: ${{ inputs.aws_region }}
-        destroy: ${{ inputs.soft_destroy }}
+        destroy: ${{ inputs.destroy }}
 
     - name: Destroy S3 Static Site Bucket for ${{ inputs.module }} ${{ inputs.environment }}
-      if: ${{ inputs.soft_destroy }}
+      if: ${{ inputs.destroy != 'false' }}
       uses: Imagimaps/common-actions/.github/actions/deploy-tf@main
       with:
         environment: ${{ inputs.environment }}
@@ -140,4 +151,4 @@ runs:
         aws_role_arn: ${{ inputs.aws_role_arn }}
         aws_account_id: ${{ inputs.aws_account_id }}
         aws_region: ${{ inputs.aws_region }}
-        destroy: ${{ inputs.soft_destroy }}
+        destroy: ${{ inputs.destroy }}
